# Generated by Django 5.0.7 on 2024-07-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'backlog'), (1, 'todo'), (2, 'in progress'), (3, 'done')], default=0)),
            ],
        ),
    ]
