# Generated by Django 5.0.7 on 2024-07-21 03:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'backlog'), (1, 'todo'), (2, 'in progress'), (3, 'done')], default=0)),
                ('importance', models.PositiveIntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], default=1)),
                ('due_date', models.DateField(default=datetime.datetime(2024, 7, 22, 11, 34, 48, 255714))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
