# Generated by Django 5.0.7 on 2024-07-21 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 11, 36, 2, 687450)),
        ),
    ]
